# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=256)),
                ('quote_valid', models.BooleanField(default=False)),
                ('quote_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
