# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='session',
            field=models.CharField(default='6te7u28496afbemq4186uz3jh1y7fw41', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.CharField(max_length=255),
        ),
    ]
