# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0002_auto_20160222_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_valid',
            new_name='valid',
        ),
    ]
