# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0003_auto_20160222_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneliners.SessionKey'),
        ),
    ]
