# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliners', '0004_auto_20160222_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionKey',
            new_name='Session',
        ),
    ]
